# Generated by Django 5.2.3 on 2025-06-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0009_customer_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_code',
        ),
    ]
