# Generated by Django 5.2.3 on 2025-06-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0011_alter_customer_options_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        )
    ]
