# Generated by Django 5.2.3 on 2025-06-24 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0012_remove_cart_customer_delete_customer'),
    ]

    operations = [
        
    
    ]
