# Generated by Django 5.2.3 on 2025-06-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0016_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avr_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True),
        ),
    ]
