# Generated by Django 5.2.3 on 2025-06-25 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0018_remove_review_avr_rating_product_avr_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avr_rating',
        ),
    ]
